name: Deploy Temp Host
on:
  workflow_dispatch:
    inputs:
      timeout:
        description: The waiting time before stopping the workflow
        required: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Docker container with Ngrok tunnel
    runs-on: ubuntu-latest

    steps:
    - name: Configure tunnel
      uses: gabriel-samfira/ngrok-tunnel-action@v1.1
      with:
        port: 8080
        ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
        tunnel_type: http

    - name: Run container
      run: timeout ${{ github.event.inputs.timeout }} docker run -p 8080:8080 ghcr.io/hsgamer/springtodolist:master
