name: Deploy Temp Host
on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Docker container with Ngrok tunnel
    runs-on: ubuntu-latest

    steps:
    - uses: Nasfame/github-actions-ngrok@v1.0.0
      with:
        timeout: 2h
        port: 8080
        ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
        tunnel_type: http
        save_url_to_filename: tunnelURL.md

    - name: Run container
      run: docker run -p 8080:8080 ghcr.io/hsgamer/springtodolist:master
