name: Deploy Temp Host
on:
  workflow_dispatch:
    inputs:
      timeout:
        description: The waiting time before stopping the workflow
        required: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Docker container with Ngrok tunnel
    runs-on: ubuntu-latest

    steps:
    - uses: Nasfame/github-actions-ngrok@v1.0.0
      with:
        timeout: ${{ github.event.inputs.timeout }}
        port: 8080
        ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
        tunnel_type: http
        save_url_to_filename: tunnelURL.md

    - name: Run container
      run: docker run -d -p 8080:8080 ghcr.io/hsgamer/springtodolist:master

    - name: Wait
      run: sleep ${{ github.event.inputs.timeout }}
